apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: osh-wus2-preprod-infra
  namespace: openshift-gitops
spec:
  description: osh-wus2-preprod-infra project
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
