apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: osh-wus2-preprod-infra
  namespace: openshift-gitops
spec:
  generators:
  - git:
      files:
      - path: apps/**/osh-wus2-preprod/*/argocd_config_auto.yaml
      repoURL: https://github.com/noseka1/gitops-example-infra.git
      requeueAfterSeconds: 60
      revision: ""
      template:
        metadata: {}
        spec:
          destination: {}
          project: ""
          source:
            repoURL: https://github.com/noseka1/gitops-example-infra.git
          syncPolicy:
            automated:
              allowEmpty: true
              prune: false
              selfHeal: true
  - git:
      files:
      - path: apps/**/osh-wus2-preprod/*/argocd_config_manual.yaml
      repoURL: https://github.com/noseka1/gitops-example-infra.git
      requeueAfterSeconds: 60
      revision: ""
      template:
        metadata: {}
        spec:
          destination: {}
          project: ""
          source:
            repoURL: https://github.com/noseka1/gitops-example-infra.git
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      labels:
        app.kubernetes.io/name: '{{ appName }}'
      name: osh-wus2-preprod-infra-{{ appName }}
      namespace: openshift-gitops
    spec:
      destination:
        name: osh-wus2-preprod
        namespace: '{{ destNamespace }}'
      project: osh-wus2-preprod-infra
      source:
        path: '{{ path }}'
        repoURL: ""
        targetRevision: '{{ targetRevision }}'
      syncPolicy:
        syncOptions:
          - ApplyOutOfSyncOnly=true
