apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: rosa-wus2-lab-apps
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: rosa-wus2-lab-apps project
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rosa-wus2-lab-apps
  namespace: openshift-gitops
spec:
  generators:
  - git:
      files:
      - path: apps/**/rosa-wus2-lab/*/argocd_config_auto.yaml
      repoURL: https://github.com/noseka1/gitops-example-apps.git
      requeueAfterSeconds: 20
      revision: ""
      template:
        metadata: {}
        spec:
          destination: {}
          project: ""
          source:
            repoURL: https://github.com/noseka1/gitops-example-apps.git
          syncPolicy:
            automated:
              allowEmpty: true
              prune: false
              selfHeal: true
  - git:
      files:
      - path: apps/**/rosa-wus2-lab/*/argocd_config_manual.yaml
      repoURL: https://github.com/noseka1/gitops-example-apps.git
      requeueAfterSeconds: 20
      revision: ""
      template:
        metadata: {}
        spec:
          destination: {}
          project: ""
          source:
            repoURL: https://github.com/noseka1/gitops-example-apps.git
  syncPolicy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: '{{ appName }}'
      name: rosa-wus2-lab-apps-{{ appName }}
      namespace: openshift-gitops
    spec:
      destination:
        name: rosa-wus2-lab
        namespace: '{{ destNamespace }}'
      ignoreDifferences:
      - group: argoproj.io
        jsonPointers:
        - /status
        kind: Application
      project: rosa-wus2-lab-apps
      source:
        path: '{{ path }}'
        repoURL: ""
        targetRevision: '{{ targetRevision }}'
