apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: rosa-wus2-stage-infra
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: rosa-wus2-stage-infra project
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rosa-wus2-stage-infra
  namespace: openshift-gitops
spec:
  generators:
  - git:
      files:
      - path: apps/**/rosa-wus2-stage/*/argocd_config.yaml
      repoURL: https://github.com/noseka1/gitops-example-infra.git
      requeueAfterSeconds: 20
      revision: ""
      template:
        metadata: {}
        spec:
          destination: {}
          project: ""
          source:
            repoURL: https://github.com/noseka1/gitops-example-infra.git
  syncPolicy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: '{{ appName }}'
      name: rosa-wus2-stage-infra-{{ appName }}
      namespace: openshift-gitops
    spec:
      destination:
        name: rosa-wus2-stage
        namespace: '{{ destNamespace }}'
      ignoreDifferences:
      - group: argoproj.io
        jsonPointers:
        - /status
        kind: Application
      project: rosa-wus2-stage-infra
      source:
        path: '{{ path }}'
        repoURL: ""
        targetRevision: ""
      syncPolicy:
        automated:
          allowEmpty: true
          prune: false
          selfHeal: true
