appName: namespaces
userGivenName: namespaces
destNamespace: default
destCluster: rosa-wus2-lab
srcPath: apps/namespaces/overlays/rosa-wus2-lab
srcRepoURL: https://github.com/noseka1/gitops-example-infra
srcTargetRevision: ""
labels: null
