apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: osh-wus2-preprod-apps-dev
  namespace: openshift-gitops
spec:
  generators:
  - git:
      files:
      - path: apps/**/osh-wus2-preprod/dev/argocd_config_auto.yaml
      repoURL: https://github.com/noseka1/gitops-example-apps.git
      requeueAfterSeconds: 60
      revision: cluster/osh-wus2-preprod/dev
      template:
        metadata: {}
        spec:
          destination: {}
          project: ""
          source:
            repoURL: https://github.com/noseka1/gitops-example-apps.git
          syncPolicy:
            automated:
              allowEmpty: true
              prune: false
              selfHeal: true
  - git:
      files:
      - path: apps/**/osh-wus2-preprod/dev/argocd_config_manual.yaml
      repoURL: https://github.com/noseka1/gitops-example-apps.git
      requeueAfterSeconds: 60
      revision: cluster/osh-wus2-preprod/dev
      template:
        metadata: {}
        spec:
          destination: {}
          project: ""
          source:
            repoURL: https://github.com/noseka1/gitops-example-apps.git
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      labels:
        app.kubernetes.io/name: '{{ appName }}'
      name: osh-wus2-preprod-apps-{{ appName }}-{{ path.basename }}
      namespace: openshift-gitops
    spec:
      destination:
        name: osh-wus2-preprod
        namespace: '{{ destNamespace }}-{{ path.basename }}'
      project: osh-wus2-preprod-apps
      source:
        path: '{{ path }}'
        repoURL: ""
        targetRevision: cluster/osh-wus2-preprod/{{ path.basename }}
      syncPolicy:
        syncOptions:
        - ApplyOutOfSyncOnly=true
        - FailOnSharedResource=true
        - ServerSideApply=true
