apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: osh-wus2-preprod-infra-infra
  namespace: openshift-gitops
spec:
  goTemplate: true
  generators:
  - git:
      files:
      - path: envs/osh-wus2-preprod/infra/**/argocd_config_auto.yaml
      repoURL: https://github.com/noseka1/gitops-example-infra.git
      requeueAfterSeconds: 60
      revision: cluster/osh-wus2-preprod/infra
      template:
        metadata: {}
        spec:
          destination: {}
          project: ""
          source:
            repoURL: https://github.com/noseka1/gitops-example-infra.git
          syncPolicy:
            automated:
              allowEmpty: true
              prune: false
              selfHeal: true
  - git:
      files:
      - path: envs/osh-wus2-preprod/infra/**/argocd_config_manual.yaml
      repoURL: https://github.com/noseka1/gitops-example-infra.git
      requeueAfterSeconds: 60
      revision: cluster/osh-wus2-preprod/infra
      template:
        metadata: {}
        spec:
          destination: {}
          project: ""
          source:
            repoURL: https://github.com/noseka1/gitops-example-infra.git
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      labels:
        app.kubernetes.io/name: '{{ .path.basename }}'
      name: '{{ index .path.segments 1 }}-{{ index .path.segments 2 }}-{{ .path.basename }}'
      namespace: openshift-gitops
    spec:
      destination:
        name: '{{ index .path.segments 1 }}'
        namespace: '{{ .destNamespace }}'
      project: osh-wus2-preprod-infra
      source:
        path: '{{ .sourcePath }}'
        repoURL: ""
        targetRevision: cluster/osh-wus2-preprod/infra
        helm:
          valueFiles:
            - ./values.yaml
            - ../../{{ .path.path }}/values.yaml
      syncPolicy:
        syncOptions:
        - ApplyOutOfSyncOnly=true
        - FailOnSharedResource=true
        - ServerSideApply=true
