apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: osh-wus2-preprod-root
  namespace: openshift-gitops
spec:
  project: default
  destination:
    name: osh-wus2-preprod
    namespace: openshift-gitops
  source:
    path: projects/osh-wus2-preprod
    repoURL: https://github.com/noseka1/gitops-example-infra.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
      prune: false
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - FailOnSharedResource=true
    - ServerSideApply=true
